### ISSUE TITLE
Security risk with root certificate?

### ISSUE THREAD

**Issue by pfiggins** [justcoding121/Titanium-Web-Proxy#105]
I'm looking at including this tool in a client's desktop application. As such, I would need to install a root certificate in order to allow for https handling. That said, is there a security risk to doing so? If so, what would be the recommended approach to making this work on an end user machine?

**Comment by justcoding121** [comment]
I would create a random unique root certificate for each installation on client machine rather than bundling one in your installation package. In that way the root certificate is not known to anyone else other than the client desktop. So if someone steals the root certificate from the desktop it can still only decrypt traffic from that specific client it was stolen from.
