### ISSUE TITLE
Request body retrieval in before response handler

### ISSUE THREAD

**Issue by aricih** [justcoding121/Titanium-Web-Proxy#136]
I need to acquire the request's body as string in my before response handler I cannot because at that point the request is already marked as locked. Any suggestions to achieve that?

**Comment by justcoding121** [comment]
You could use a dictionary with a composite key of client IP, client Port, Url and set its request body before request. After request you can look it up then. This is not the best way, we need to add a Guid property to identify each session in future.

The reason why we are not allowing to read request body after request is because its a volatile content. And its not safe from memory perspective. We read the data and send it to server without saving it anywhere. If user requested the body before request, its in their until the end of session. 

So I think we need to make updates to generate and set a Guid for each session, which the user can use as key for his request body dictionary.

**Comment by justcoding121** [comment]
Added RequestId property in latest commit

**Comment by GF-Huang** [comment]
> The reason why we are not allowing to read request body after request is because its a volatile content.

Why it is a volatile content?

**Comment by GF-Huang** [comment]
How can I get request body in `BeforeResponse` now?

**Comment by honfika** [comment]
The request body can be big, this is why TWP is not storing it unless you explicitly read it in the beforerequest handler. Why is it a problem for you to add a BeforeRequest handler and sotre the request there?

**Comment by GF-Huang** [comment]
Solved by `UserData`, thanks.
