### ISSUE TITLE
About NTLM/Kerberos

### ISSUE THREAD

**Issue by aricih** [justcoding121/Titanium-Web-Proxy#139]
What is the exact situation on ntlm-kerberos branch? Will it be released soon?

**Comment by aricih** [comment]
Do you recommend merging that branch into current release branch as it is?

**Comment by justcoding121** [comment]
Its not even complete. I just added some code files to start with it. If you are interested you can copy those files specific to NTLM/kerberos.

I dont think its a good idea to merge it, because it was my incomplete work branch.

**Comment by justcoding121** [comment]
Since NTLM/Kerberos is not expected to run when client is from remote machine, we can perhaps use [HttpWebRequest ](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.95).aspx) to make a fake request to server when we receive Windows authentication challenge from server. (and client is from local machine). And then we can use reflection to find out the token from HttpWebRequest object after final authentication and then use that token in our subsequent request headers. I think this is the way fiddler accomplishes the same.

Otherwise one will have to write all the code for NTLM/Kerberos by making native calls to Windows API. [This repository](https://github.com/justcoding121/Nancy.Authentication.Ntlm) may help. @honfika If you are interested, this is open.

**Comment by justcoding121** [comment]
Added support in latest dev
