### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by OlsonDev** [justcoding121/Titanium-Web-Proxy#146]
Just curious if you planned on adding .NET Core support and if so, how difficult it'll be?

**Comment by justcoding121** [comment]
I don't think it would be difficult. The solution file probably will need to have to be updated to support packages.json file used for nuget in .NET core. And I am not sure at this point if it supports all API's we use here from .NET 4.5

**Comment by coosmiin** [comment]
So.. should we understand from this that you are planning to do it sometime in the near future?

**Comment by justcoding121** [comment]
I don't think so. I tried moving the code to a PCL or .Net Standard 5/6 class library Project. Have hard time with numerous errors on VS 2015 complaining about things that didn't made any sense. 

I would be happy to merge if any .Net Core geeks out there can perhaps make a pull request to port this project so that we can have it build for both .Net Core and .Net 4.5.x or .Net 4.6.x.

**Comment by adminnz** [comment]
I've tried to port this to .Net Standard 1.5. I removed all the windows specific stuff.

But I keep getting an exception in the RequestHandler when it calls 
```
await sslStream.AuthenticateAsServerAsync(certificate, false, SupportedSslProtocols, false);
```
With the exception being: 

> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

I had to modify the BCCertificateMaker because X509Certificate2 does not have a PrivateKey but even if I bypass the certificate maker and just get it to load the certificates from disk (both the root and the signed domain certificate) it fails.

I have tried running a .Net Standard titanium proxy server and then doing the following:

- Run a .Net Framework client that communicates with the .Net Standard proxy service. This works fine.
- Run a .Net Core client that communicates with the .Net Standard proxy service. This fails.

So I don't believe its an issue with the proxy server, but how the SslStream is actually authenticating between the proxy server and .Net Core's HttpClient.

I have attached a solution that has the following:

- Titanium.Web.Proxy (.Net Framework)
- Titanium.Web.Proxy.Standard (.Net Standard 1.5)
- Examples/Framework.Client (.Net Framework Console App)
- Examples/Framework.Server (.Net Framework Console App using Titanium.Web.Proxy)
- Examples/Standard.Client (.Net Core 1.1 Console App)
- Examples/Standard.Server (.Net Core 1.1 Console App using Titanium.Web.Proxy.Standard)


[Solution.zip](https://github.com/justcoding121/Titanium-Web-Proxy/files/1073452/Titanium.Web.Proxy.zip)

**Comment by honfika** [comment]
@adminnz : I've created a pull request based on your changes. It was already merged to the repository develop branch.
Please check the following project:
Titanium-Web-Proxy\Titanium.Web.Proxy\Titanium.Web.Proxy.Standard.csproj
It is not added to the solution. I did not fixed anything, just merged the changes. Your example projects are not added.

**Comment by justcoding121** [comment]
.net core is currently supported in stable release
