### ISSUE TITLE
Access denied - StoreLocation.LocalMachine (develop)

### ISSUE THREAD

**Issue by OC-Carl** [justcoding121/Titanium-Web-Proxy#196]
So I tried to use the develop branch and ran into {System.Security.Cryptography.CryptographicException: Access is denied.     at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)    at Titanium.Web.Proxy.Network.CertificateManager.TrustRootCertificate(StoreLocation storeLocation, Action`1 exceptionFunc) in C:\Users\XXXXXXX\Titanium\Titanium-Web-Proxy-develop\Titanium.Web.Proxy\Network\CertificateManager.cs:line 233}

The suggested work around is to code impersonation.  Is this being planned for future implementation or do you have a different trick up your sleeve?

**Comment by justcoding121** [comment]
Isn't the error getting cached and logged and the proxy continues to work? 

That error is expected when proxy is not running under user having Local Administrator privilege. (Try running Visual Studio as Administrator). Proxy tries to install the Root Certificate to Local Machine. (This is so that FireFox can detect it).

Regardless it shouldn't be a problem for catching traffic as usual for chrome, IE, edge and Opera. Because those browsers look at Local User store, and proxy will install it. (You will get a dialog from OS to install certificate when you run the proxy first time)

**Comment by OC-Carl** [comment]
>That error is expected when proxy is not running under user having Local Administrator privilege.

That is why I was asking about impersonation.  Coding what is necessary instead of running a future stable release version w/ elevated privileges.

>This is so that FireFox can detect it see #180

Thanks.  I wondered why it was added.

>Did you try continue debugging on Visual Studio.

Actually I use Xamarin Studio.  I was concerned about it not being added to Local Machine as the program seemed to expect.

You may ask why Xamarin Studio?  I want to run TWP on a Mac.  I successfully conditionally compiled 
a previous stable version running for HTTP.  But I ran into strangeness w/ HTTPS.  I see you have added Bouncy Castle for Mono, so I used the develop branch to determine what effort it would be to run on OSX with Mono, if possible.  (No expertise in crypto, yet.)

You added "help wanted".  What do you have in mind?

**Comment by justcoding121** [comment]
Okay. There is a bug in last release. 

I categorize the threads to find the priority, I've added now bug label. Thanks for reporting.

**Comment by OC-Carl** [comment]
>exception func passed as null

That too.  But what about the base problem of "access denied"?

Are you expecting the proxy will be run w/ elevated privileges?

I like the idea of setting impersonation around the few lines necessary to complete the operation?

I was wondering if you had any other tricks up your sleeve?  What are your plans?

Before do anything, I want to get your input as to the direction you intend TWP should go.

**Comment by justcoding121** [comment]
The "access denied" issue was intended to be as it is.  The idea was that user can find the reason why Firefox failing to use the proxy, since as per documentation it looks at System certificate store. But it appears Firefox won't use system certificates even after being installed to Local Machine store.

**Comment by justcoding121** [comment]
Running the proxy as impersonated elevared user who has permission to install certificate to local machine may also avoid the exception. But I am not sure if code for that should be added to proxy, while it can be done from outside if required.
