### ISSUE TITLE
Why is TWP all async?

### ISSUE THREAD

**Issue by OC-Carl** [justcoding121/Titanium-Web-Proxy#197]
Just wondering the design decision behind using async routines within TWP.

The responses received usually do not match the requests made by a browser.

I like the OnRequest & OnResponse events to trigger my custom code, but it seems like I have to do a lot work so I can understand which response goes with which request.

Because I could, I modified all async routines so TWP behaved in a synchronous manner.  Kind of what I was expecting, so I have been wondering several months now why TWP was designed to be async?

**Comment by justcoding121** [comment]
May be I need to get a coffee in morning first can you please elaborate TWP?

**Comment by justcoding121** [comment]
If I understood this right, please note that the proxy is multithreaded, and request/response handlers will be fired as soon as we receive data from client/server asynchronously. It won't be in order. To figure out the order #136 will help, by using the RequestId property.

**Comment by justcoding121** [comment]
Regarding your why async design question, async is used to improve cpu usage in high traffic situations. Otherwise there will be a bunch of threads waiting for network I/O to complete, while in async design such threads are free to do other tasks. It is no differant than the reason why many asp.net applications use async. 

Again its a design choice and in my experience if not properly understood by developers broken implementations of async can cause problems.

**Comment by OC-Carl** [comment]
I kinda figured async was done for speed.  It makes sense to pass thru requests and receive whatever response, rather than waiting to receive a response before sending the next request.

What really helps is your reference to #136.  I see now how RequestId can be used to "sync" request with response, as though processing was done sequentially.  Thanks for the push in the right direction,
