### ISSUE TITLE
"Your connection is not private" in Chrome

### ISSUE THREAD

**Issue by maruashok** [justcoding121/Titanium-Web-Proxy#199]
From last few days i am receiving error like "Your connection is not private" in Chrome.
My chrome version is 58.0.3029.81 .

but if i use Google Chrome 52.0.2743.116  than it  works perfect,

i try latest stable build Titanium web proxy 3.0.8 but facing same issue.

Is there any solution for it..?

**Comment by aricih** [comment]
Chrome deprecates subject cn matching with version 58. It's explained here; https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/

@justcoding121 you have to add hostnames as subject alternative name to the certificates now. We've added this one with our implementation too.

**Comment by justcoding121** [comment]
@aricih Thanks for this great input. This also explains why Firefox throws error #180 . When I switched to BouncyCastle Firefox stared to work for secured sites. 

@maruashok If you are okay with Bouncy Castle give a try.

`  proxyServer.CertificateEngine = Network.CertificateEngine.BouncyCastle;`

Now the problem here is to make this supported with our [windows certificate maker](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Network/Certificate/WinCertificateMaker.cs) which somebody wrote.

**Comment by justcoding121** [comment]
Fixed windows certificate maker as well to support alternative names in latest Beta.

**Comment by justcoding121** [comment]
@aricih You mentioned that you've added alt name to[ your implementation](https://github.com/netsparker/Titanium-Web-Proxy/blob/beta/Titanium.Web.Proxy/Network/CertificateMaker.cs). I cloned the same file in to this repo for Bouncy Castle, but when I view the certificate it don't have alternative names. I am not yet on chrome 58. 

The reason for Firefox failing with WinCertificateMaker was actually because of wrong issuer name which I fixed just now. But since it is working without alt name specified from BouncyCastle cert maker just wondering.

**Comment by maruashok** [comment]
ok bro i am trying latest beta by implementing proxyServer.CertificateEngine = Network.CertificateEngine.BouncyCastle;

i am using titanium to block all request other than white listed sites,  i think its difficult to  implement SubjectAltName for all hostname, and i don't have more idea about it what does it mean.

**Comment by aricih** [comment]
@justcoding121 as I mentioned before we moved the code to our private repo for a while now. For instance we even don't use BouncyCastle anymore, we're using Mono.Security instead. I'll sync proper parts of the public repo with it as soon as possible.

**Comment by justcoding121** [comment]
Thanks @aricih 

@maruashok Actually it should be working for both CertificateEngines in latest release.
