### ISSUE TITLE
OnRequest handler getting called multiple times for the same request when using SSL

### ISSUE THREAD

**Issue by MisterAcoustic** [justcoding121/Titanium-Web-Proxy#268]
Hi,
I just upgraded to v3.0.37 of the proxy, and I started working with our site over a secure connection.

I am seeing my OnRequest handler get called multiple times for the same actual request. Sometimes there is only one extra call, but I have seen up to seven. Using the chrome devloper tools alongside my proxy app, the networking tab shows that only one request was made. Separately, I tried Fiddler, and only saw the one request.

The problem does seem to be intermittent, but seems to happen more often than not.

I have NOT seen similar behavior when only using http instead of https.

Any help is appreciated. If you would like more information, let me know what I should do.

Thanks.

(Edit: Forgot that I renamed OnRequest to RequestHandler for my code)

**Comment by justcoding121** [comment]
Are you setting `proxyServer.EnableWinAuth` or setting `ReRequest` anywhere?
Is there a public URL as a sample for this problem?

**Comment by MisterAcoustic** [comment]
I will check to be certain when I get back to work tomorrow, but I do not believe I set either of those things. I will look into making the site available to you (it should be possible).

In case anyone else is seeing this problem, I am working around it currently by discarding any requests for which I do not have a response. Since there is only one real request, and it does have a response, this is working fine in my situation.

I will get back to you tomorrow.

Thanks!

**Comment by MisterAcoustic** [comment]
Hello,

I confirmed that I am not setting either EnableWinAuth or ReRequest.

Here is a site where I can reproduce the problem: https://demo1.mye2shop.com/

Steps to reproduce:
-In Chrome (I was using Version 58.0.3029.110 (64-bit), but just updated to Version 59.0.3071.86 (Official Build) (64-bit)), go to the site.
- Start the proxy app, and start listening
- Reload the site (status bar says Establishing secure connection...)
- Enter values for username and password (stan and none will be fine - you don't even need to successfully log in)
- Click Login. This sends a single request to CheckCredentials, however, most of the time, my OnRequest handler is called at least twice. The requests come in with two separate ids. Curiously, it's the first request that never receives a response. The second request usually completes normally.

Once you have the site url, could you either edit it out, or let me know so I can remove it?

Hope this helps,
Stan

**Comment by justcoding121** [comment]
Okay what I saw was that server [returns empty (null) response](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Http/HttpWebClient.cs#L162) for some requests, and in turn that error causes the proxy to drop the client connection. Now client (browser) immediately keeps on retrying the same request (even though I don't see that being logged in chrome tools) when this happens. 

If you are logging the proxy errors (like in the example project) you will see that every time this multiple requests happens, an accompanying error is also logged in proxy.

Now why server abruptly terminates the connection I am not sure. One guess is connection timeout is too short on server.

**Comment by MisterAcoustic** [comment]
Do you mind if I ask how you saw the extra requests? As you noted, the chrome developer tools don't show them, and I also did not see them when proxying with Fiddler. Do I need to resort to wireshark? I'd like to be able to see what's happening for myself, so I can pass along the information to the team developing the site.

**Comment by justcoding121** [comment]
I saw the extra requests happening from Chrome to this proxy.

What I observed is that the browser is retrying the same request when server connection fails. Chrome developer tools only show one request and logically its correct, since developer probably don't want to see a transport error like this (as opposed to an application error). You can step through the code if you like to debug.

Now as far as fiddler I believe it is only showing those requests which actually succeeded, but here we are not hiding anything from developer.

If it is indeed a timeout problem it is nothing to worry about. I guessed 10 seconds because I noted this happening only if I wait more than 10 seconds and attempt to submit login from the website. Browsers are inherently prepared to handle a connection timeout. And that's why the website is functioning okay (?) from users perspective. But if you like to avoid this happening too often, check the default Http Keep-Alive timeout on server. For example in IIS the default is 120 seconds. In this proxy server we have default 30 seconds, but you can [always increase it](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L285). But proxy connection timeout will be hit later than server if server have something less than 30 seconds. Or another option is to disable keep-alive on server, which defeats the purpose of the enhancement in HTTP 1.1.

**Comment by MisterAcoustic** [comment]
Thanks again for you help. The team tells me there is a load balancer in front of the web servers that might be causing the problem, but also that a move to a new hosting environment is happening shortly. So, we will look for the problem if it appears in the new environment, and deal with it then.
