### ISSUE TITLE
How to use different ExternalProxy for each https request ?

### ISSUE THREAD

**Issue by GreatFireWall** [justcoding121/Titanium-Web-Proxy#313]
In my test, when the first https request had responsed, the second request doesn't call ProxyServer.GetExternalProxyFunc.

I had try the following code, but not work:
```
private async Task OnBeforeRequest(object sender, SessionEventArgs e) {
    e.CustomUpStreamHttpProxyUsed = myProxy;  
    e.CustomUpStreamHttpsProxyUsed = myProxy;  
}
```

**Comment by justcoding121** [comment]
We don't yet support each HTTP request from a single client TCP connection to use different up stream proxy. However we do support changing stream proxy on a per connection basis. That's why you see the call is getting hit only once at the beginning of connection establishment to server and not for subsequent HTTP requests over same TCP connection from client. The reason we haven't given much interest to do the same have to do with performance.

You may be aware that typically a series of HTTP request/response sequence is done over a TCP connection from client to proxy and then from proxy to external proxy. If you keep changing the up stream proxy for each HTTP request from same client TCP connection then the proxy would have to drop existing TCP connection to server and create new one. This will greatly affect performance defeating the purpose of HTTP 1.1 keep-alive feature.

Ideally a single connection from client should be piped to a single connection to same up stream proxy for HTTP keep-alive functionality to accomplish its purpose.

Having said that a way to mitigate the overhead would be to use a TCP connection cache in proxy. I think one day when we implement the cache we would support this feature.

**Comment by justcoding121** [comment]
Meanwhile if any one is interested in doing a short term solution to this by dropping and creating server connection when external proxy changes this is up for grab. That would mean calling GetCustomHttp(s)ProxyFunc methods for each request.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L588

**Comment by GreatFireWall** [comment]
Great, Thanks your guide.  I try to modify this.

**Comment by honfika** [comment]
No, they are set when the server connection is created.
But it contains only the the result of your `GetCustomUpStreamProxyFunc` call.

**Comment by miroslavp** [comment]
> Meanwhile if any one is interested in doing a short term solution to this by dropping and creating server connection when external proxy changes this is up for grab. That would mean calling GetCustomHttp(s)ProxyFunc methods for each request.
> 
> https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L588

The link is broken :( (404)

**Comment by justcoding121** [comment]
See https://github.com/justcoding121/Titanium-Web-Proxy/issues/512

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.

**Comment by POMATu** [comment]
all links leading to the actual piece of code dead once again

**Comment by honfika** [comment]
Ok, but if you are a developer, it should not be hard to find a class in the repository at the given date...
Here it is:
https://github.com/justcoding121/titanium-web-proxy/blob/572866b497fb51d8a5fc90a61a6d2b260bbf9cf8/Titanium.Web.Proxy/RequestHandler.cs#L588

And the latest version:
https://github.com/justcoding121/titanium-web-proxy/blob/1236dceabd8aff639e56eea2de7fbe678729a339/src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L111-L135
