### ISSUE TITLE
How to detect file download request

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#323]
I have a situation where I need to block all file download request/response from web on the system which is running Titanium-Web-Proxy. 
How can I identify all those requests/responses to block them.

**Comment by honfika** [comment]
I think you can detect only the response. The request is the same for the web pages and the downloads.
You should chekc the Content-Dispositionheader.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

What is the reason? You won't save bandwith between the server and the proxy, since the file will be dowloaded to the proxy. You can save bandwith between the client and the proxy.

**Comment by honfika** [comment]
Or you can close the connection after you detect the header. I don't know whether it is currently possible with Titanium or not, but it is technically possible, just let me know and I'll add a CloseConnection or similar method to the response received event.

**Comment by harrip12** [comment]
Thanks,
I need to identify the request/response which if for file download and stop user from file downloading by blocking that request/response. 
I tried Content-Disposition in response headers, but many response doesn't contain Content-Disposition header.
Right now I am doing it by comparing content-type in response header with MIME type, but it is not applicable for all sites, in some of the sites it is getting failed while downloading a file.

**Comment by honfika** [comment]
In this case you can check only the content type or the file extension in the request url (but it will work only for static file urls)
This is the HTTP protocol, everything is a file, an image in a webpage is a file, too.

**Comment by harrip12** [comment]
ok. I wonder how commercial firewalls understand a download request and block them.
