### ISSUE TITLE
SessionEventArgs manually disposed

### ISSUE THREAD

**Issue by fabricedupre** [justcoding121/Titanium-Web-Proxy#326]
I would like to keep track of the WebSession objects (got from SessionEventArgs) during a particular http dialog.
I keep a reference of them in a list, but unfortunately, the SessionEventArgs are manually disposed in HandleHttpSessionRequest and this by consequence diposes the WebSession as well.

Is there any reason for doing that (calling args.Dispose()) ?
Why don't let he GC do the job ?

**Comment by justcoding121** [comment]
Some methods inside WebSession will become dead after the end of connection since those are meant to be called when the session is still active. 

See below discussion.
https://github.com/justcoding121/Titanium-Web-Proxy/issues/280

Having said that it should be possible to keep the objects separately using you own data structure. Can you show the code? Take a look at the examples below where we keep the header collection and other details for future reference but not the WebSession itself.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/5517830ea89fca001a42e24e49e033b7fddf887c/Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs

**Comment by fabricedupre** [comment]
Unfortunately, that's the WebSession itself which I'd like to keep (more specifically Request and Response fields).
I have commented out all the args.Dispose from HandleHttpSessionRequest and all seems to be ok (I can access the Request/Reponse properties). I understand that once the session is closed, some methods will fail.
See attachment (BTW, would be nice if properties had the ExpandableObjectConverter attributes :-)
![capture](https://user-images.githubusercontent.com/13865291/32727825-5477f0ae-c87e-11e7-918e-c5a63e95e3c9.PNG)
)

**Comment by justcoding121** [comment]
We may be able to keep the object alive in future, but throw exceptions when accessing methods/functions which are no longer valid.

**Comment by honfika** [comment]
Could you pleses check my https://github.com/justcoding121/Titanium-Web-Proxy/commit/5d2bf63558e9bef2cd32b29680d6289b5f6e898c commit?
The `SessionEventArgs` is still disposed, but the `WebSession` (`HttpWebClient`) is not.

I made some existing properties to public (get only):
`Request.RequestBody` and `Response.ResponseBody
`Request.RequestBodyRead and `Resposne.ResponseBodyRead`

These properties were internal earlier, I've added a check which throws exception when the body is not read, yer or already streamed without storing it.

When the session is finised the body is cleared by default. I've also added 1-1 new properties to keep the body (and body as string): `Request.KeepRequestBody` and `Response.KeepResponseBody

`I'd like to rename some proerties, what do you think about it?
`Request.RequestBody` => `Requet.Body`
`Request.RequestBodyRead` => `Request.IsBodyRead`
`Request.KeepRequestBody` => `Request.KeepBody`
(and the same for the Respose class)

This would not be a breaking change, since they were internal in the last release.

**Comment by honfika** [comment]
There are some more properties which could be renamed, but it would be a breaking change:
`ResponseStatusCode`
`ResponseStatusDescription`
'ResponseKeepAlive'
`ResponseHeaders`
`ResponseStatus`
And the similar properties i nthe `Request` class.

**Comment by fabricedupre** [comment]
Hello,

 

Just curious, why don’t you simply not dispose the SessionEventArgs ?

**Comment by honfika** [comment]
I think nobody should save a reference to an `EventArgs` object (not only in this case). For the user's perspective it is valid only in the event handler.

**Comment by fabricedupre** [comment]
Makes sense :-)

**Comment by fabricedupre** [comment]
That makes RequestBody/ResponseBody throw an exception even if it does not have body. What about returning null if HasBody is false ?

Also for RequestBodyString/ResponseBodyString, null could be returned if body is null to prevent an exception being thrown.

**Comment by justcoding121** [comment]
@honfika  I don't mind renaming the properties you mentioned.

**Comment by honfika** [comment]
I don't mind returning null when HasBody is false. But SessionEventArgs.GetRequestBody/String methods also throws exceptions. I think it should be the same.
However the GetRequestBody throws BodyNotFoundException while Request.RequestBody throws Exception with message "Request body is not read yet. Use SessionEventArgs.GetRequestBody() or SessionEventArgs.GetRequestBodyAsString() method to read the request body.", so it is a bug, it should be the same.

@justcoding121 What do you prefer?
- throw BodyNotFoundException as it is implemented now in the SessionEventArgs.Get methods
- or return null in this case?

@fabricedupre Why is it a problem if it throws an exception? You can prevent it by checking the HasBody property.

**Comment by justcoding121** [comment]
I would throw the exception rather. 

Like you said developers can always check for the body and the exception message is self-explanatory. They tried to access the body without knowing that not all HTTP requests/responses have a body.

**Comment by fabricedupre** [comment]
When displaying the Request/Response in a PropertyGrid control, there is no way to check for the body
PropertyGrid can anyway survive such properties throwing exception, but this is at the cost of performance slowdown.

**Comment by honfika** [comment]
You can hide the Body property in the PropertyGrid:
https://stackoverflow.com/questions/18926109/c-sharp-net-4-5-propertygrid-how-to-hide-properties

I did not try it, but in this case the getter should not be called.
Displaying a huge body and converting it to a string and displaying that string, too is a performance slowdown, too... so you should hide it. (And I think you don't need them, because it wasn't available earlier)

Or if you want to show the body, I suggest you to wrap the object to another which just returns the "small" properties and the body looks like:
```
        public byte[] RequestBody
        {
            get
            {
                if (!HasBody)
                {
                    return null;
                }

                var body = webSession.RequestBody;
                if (body.Length > 1000)
                {
                    return body.Take(1000).ToArray();
                }

                return body;
            }
        }

```

**Comment by fabricedupre** [comment]
I am more than happy to have the RequestBody (/ResponseBody) marked as non browsable as far as the corresponding string is browsable and does not throw an exception

**Comment by honfika** [comment]
I think that the corresponting BodyString property will throw an exception, since it just converts the byte[] to string:
        public string BodyString => bodyString ?? (bodyString = Encoding.GetString(Body));

**Comment by fabricedupre** [comment]
That's why I suggested returning a null string in case body is null
Or mark it as non Browsable and let the developper handle the logic ...
Also, still linked to PropertyGrid, would it be possible to mark the HeaderCollection with the attribute [TypeConverter(typeof(ExpandableObjectConverter))] ?

**Comment by honfika** [comment]
Put it to the class?

```
    [TypeConverter(typeof(ExpandableObjectConverter))]
    public class HeaderCollection : IEnumerable<HttpHeader>

```

For me it is ok.

**Comment by fabricedupre** [comment]
Exactly :-)
And same can be done on class Request / Response

**Comment by honfika** [comment]
Could you please check this commit?
https://github.com/justcoding121/Titanium-Web-Proxy/commit/250a081ece38f8899f0ac20df2d206c2b92b9648

**Comment by fabricedupre** [comment]
Works fine :-)

**Comment by justcoding121** [comment]
Looks okay.

**Comment by honfika** [comment]
Then I close this issue.
