### ISSUE TITLE
Wildcard ssl hostname problem

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#352]
I noted that below website fails with a Ssl certname mismatch message in chrome.

Try to click **continue with GCKey button** on the page.
https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html

Currently we generate a certificate named ***.gc.ca**. But if we generate one without wildcard it succeeds (**clegc-gckey.gc.ca**). 

I am not sure if it has anything to do with the dash (-), if so we should avoid creating wildcard certificates when hostname has a dash in its prefix. I noted fiddler do not generate wildcard certificate for this website, may be it also checks for dash.

**Comment by honfika** [comment]
It seems to work now, so I close this, thanks:)

**Comment by keskino** [comment]
Hi All, first, thank you for you effort creating such a great proxy, about the above problem, actually it is not related to dashes in the urls, it is actually a problem in the wildcard certification generation mechanism, which only occurs when a url with 2 TLDs (like .co.nz or .co.uk or .com.tr) does not redirect to "www". As an example you can try "https://yandex.com.tr" which will create the certificate with "*.com.tr" which is invalid. So the issue persists. 
As a suggestion, a static TLD list can be kept in memory to check if cropped domain is one of them, if so return the original host name instead of wildcard domain name. You can find top level domain extensions here : https://wiki.mozilla.org/TLD_List

**Comment by ewwink** [comment]
the commit is not valid, `gc.ca` is not host but second-TLD. 
updated public suffix https://publicsuffix.org/list/public_suffix_list.dat
