### ISSUE TITLE
Improve network write efficiency (TcpNoDelay / buffering)

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#425]
can we get a `UseTcpNoDelay` property on the `ProxyServer` that would apply to all client and server connections?  this can help reduce latency in some cases.  thanks.

edit: or perhaps a callback that includes any newly created TcpClient so i can tweak it however i want (eg nodelay, buffer sizes, etc)

edit2:
I've stepped through the code a bit and would recommend the following in conjunction with the TcpNoDelay flag:

`HttpWebClient.SendRequest` does line by line writing of the HTTP request line and headers.

There is no application level buffering of these writes -- they each result in a system call to write data to the network stream.

Depending on timing of things the o/s may aggregate these in its socket send buffer or it may result in multiple network packets being sent (especially with TcpNoDelay set).

So, there really should be some buffering on top of the network stream.

In fact, there already exists a buffer in `HttpWriter` but it's only used for string -> byte conversion.

Probably the best thing would be to have a version of HttpWriter.WriteLineAsync() that only calls `Write` on the network stream once the buffer is full and requires the caller to do a `Flush` when he is done to push any residual data.

If you want, I can code it up and provide a pull request provided you agree with this approach.

edit3:
Ok, spotted that the `NetworkStream` is actually wrapped in a `CustomBufferedStream` but looks like the buffering is on the read side only

**Comment by justcoding121** [comment]
The reason we have a `CustomBufferedStream` is because 

1. No streams in dotnet supports reading both bytes/string on demand from network stream from the last read position.
2. We want to implement async support with ReadBytesAsync & ReadStringAsync but with an underlying buffer to avoid async calls for short number of bytes.

As you noted this is implemented in StreamExtended library specifically because we needed it there as well. 
https://github.com/justcoding121/StreamExtended/blob/master/StreamExtended/Network/CustomBufferedStream.cs

You would need to create any PRs there. Specifically @honfika wrote that stream, so he may be able to provide his thoughts.

A callback for newly created Tcp connections to find tune connection is a good idea if you are up to implement it. Something like `proxyServer.OnTcpServerConnectionCreate` following existing event convention for other similar events would do.

**Comment by justcoding121** [comment]
@honfika Do you think we will get any improvement by adding a Write buffer in `CustomBufferedStream`. I personally don't think so. Because as I see it we are calling WriteAsync for HttpStatus, HttpHeaders (by combining all headers in to a string using StringBuilder) and then the body using local buffers. 

If there is any spot  we are unnecessarily calling Flush/FlushAsync would be worth looking.

**Comment by jgilbert2017** [comment]
@justcoding121 can you point me to the code that combines the headers into a StringBuilder?  May not be as big a problem as I initially thought b/c SslStream likely does buffering in order to do the encrpytion but could still be an issue when using http.

The real test would be to step through the code and run wireshark to watch network activity.  ideally you are only sending out packets that are full or at the end of a request.  On the read side you want to make sure you are making o/s socket read requests on a buffer (at least 4k) and then processing from the buffer.

I think I'm going to work on my app logic before researching this further.

**Comment by justcoding121** [comment]
You are right. I thought we are using stringbuilder to combine all headers and then calling WriteAsync once. But apparently we are not.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/Helpers/HttpWriter.cs#L107

We would have to Flush at least three times on write. 

1. After writing response status
2. After writing headers
3. After writing body if response has a body 

Steps 1 & 2 can be potentially combined to one. For step 3, its already buffered so WriteAsync is called once write buffer is full or after end of response.

**Comment by justcoding121** [comment]
I updated `HttpWriter` to combine headers using `StringBuilder` and then do one single `WriteAsync`. Also added two events `OnClientConnectionCreate` and `OnServerConnectionCreate` which would be fired with `TcpClient` as payload when client connection is received and server connection is created respectively.

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.
