### ISSUE TITLE
TcpClient.LingerState should probably be set on creation

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#426]
`TcpExtensions.CloseSocket()` is setting `LingerState = new LingerOption(true, 0)` conditional on a reflective check of a private property `TcpClient.CleanedUp` which corresponds to whether Dispose/Close has already been called on the socket.

I think a better option would be just to set the `LingerState` directly after creating the `TcpClient` in all cases.  Otherwise we risk the socket being closed/disposed internally by the TcpClient class before we get a chance to set it.

**Comment by jgilbert2017** [comment]
@justcoding121 i think you're right on this one... just re-read on it and you only want to do a RST on a forcible close due to an error. 

There shouldn't be much  chance of sending data to the wrong client though (the TCP seqnums will not match).

(Connection pooling would be awesome!)

**Comment by honfika** [comment]
@justcoding121 Sorry, I don't know this, but the connection pool seems to be a good idea.

**Comment by justcoding121** [comment]
I implemented connection pool and by default it is disable with flag `proxyServer.EnableConnectionPool`. The reason being our inability to identify if the remote server closed the connection when we retrieve from cache. Only when we write data it will be evident. The connection pool works fine in my testing, but randomly I see client connection getting closed due to the above reason.

This would mean we need to add the feature to retry requests when server connection fails by retrying first write after getting the connection.

**Comment by justcoding121** [comment]
Please take a look if I missed something in connection pool implementation.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs

**Comment by jgilbert2017** [comment]
@justcoding121 cool.  i can't really put it through it's paces right now but some feedback:
- probably want to use try/finally with all lock operations (eg wait/release) to avoid issues if exceptions are thrown.
- should the cache key include isHttps?
- private bool runCleanUpTask should probably be declared volatile since there is no locking across threads

**Comment by justcoding121** [comment]
Updated thanks.
