### ISSUE TITLE
Use of Guid as a session identifer

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#427]
I believe `Guid.NewGuid()` is a pretty heavy weight call.

From what I can tell, the only use of the `RequestId` (which is currently a `Guid`) is to be used as a key into a hash table.

For this purpose `new object()` would suffice or probably `sealed class RequestId {}` for type safety.

**Comment by justcoding121** [comment]
So that would mean that we using the pointer to an object as a key. Right?

**Comment by justcoding121** [comment]
@honfika

**Comment by justcoding121** [comment]
Actually using just a long/int starting from negative max should be fine too. Unless of course the long integer reaches the max limit which is very unlikely.  Just to be safe we can reset to to -ive max if that does happen. :-)

We would need to use an interlocked long counter may be to prevent duplicates.

**Comment by jgilbert2017** [comment]
are you sure we even need an id? 

- if you need to hash why not just hash off the `WebSession` object?
- alternatively, if the API user needs to associate data on a per `WebSession` basis, how about just adding a `public object UserData { get; set; }` property to the `WebSession`.  this avoids issues with object lifetimes that the hashing approach creates

**Comment by justcoding121** [comment]
We had complaints about not having Id in past. Specifically because without an Id there is no connection between request & response WebSession objects since they happen asynchronously. May be because of lack of examples. HashSet<WebSession> would actually do the job if user wants to keep track of it. I am okay with removing the property completely.

If we did keep the `RequestId` property I think `int` is the most simplest and yet performance wise good choice (much better than a Guid). With objects as `RequestId` it is little bit costlier create an object.

Using an extra property to keep user stuff, I am not supporting that. It gets little dirty. If user wants to keep custom data with a session they can always use a `Dictionary<WebSession, CustomData>`.

**Comment by jgilbert2017** [comment]
I didn't realize the request and response WebSession objects were different. 

The guid is created in the WebSession (HttpWebClient) ctor.

Can you please explain how the request/response is matched right now if they are different?

**Comment by justcoding121** [comment]
They are the same objects per Http request/response session. But since events happen asynchronously we cannot predict the sequence they get fired, that's what I was mentioning a few users had difficulty understanding.

Request A gets fired (WebSession A)
Request B gets fired (WebSession B)
Request B gets response (WebSession B)
Request A gets response (WebSession A)

So as you can see in the example in home readme we use RequestId explicitly, but like I said actually a HashSet<WebSession> would do the job.

**Comment by jgilbert2017** [comment]
So yeah... i don't see the need for an id.  If you need to hash, just use the `WebSession` object as the key.  I don't really understand the use case for a HashSet of WebSessions.  But are you sure you are opposed to the `UserData` property.  I can definitely envision a case for this and the hash table approach is going to be prone to memory leaks.

**Comment by justcoding121** [comment]
Would using a `Dictionary<WebSession, CustomData>` would satisfy the need? Add item to list once a new session arrives, remove when its over. @honfika Your thoughts would be appreciated for using an additional object property called UserData.

**Comment by jgilbert2017** [comment]
The `Dictionary` approach would work but if for some reason (lets say an obscure bug) you missed the callback that indicates "its over" you wind up leaking `WebSession` objects which I suspect are pretty big.  It also saves you an extra hash lookup (which is synchronized so a potential bottleneck).

**Comment by honfika** [comment]
I think an object UserData property is a good idea. I don't mind the Id or the type of the Id.. I don't need it anyway:)

**Comment by justcoding121** [comment]
Okay. Lets remove the Id property then and add UserData object.

**Comment by honfika** [comment]
Object UserData property was added. I've added an internal Data property, too, which is a dictionary, because WinAuthHandler used the requestid as a dictionary key. Now it stores the state data in the internal data property.

**Comment by justcoding121** [comment]
Okay. That's even better. I was thinking we might need an internal dictionary to keep original accept-encoding when I was looking at other issue at #428 .

**Comment by justcoding121** [comment]
Please reopen if any issue arise.

**Comment by jgilbert2017** [comment]
big ups for `UserData`.  going to be very useful for my app logic.  i appreciate your responsiveness!  kudos!!!
