### ISSUE TITLE
Explicitly specify a list of hosts for proxy

### ISSUE THREAD

**Issue by marcfielding1** [justcoding121/Titanium-Web-Proxy#43]
Hi Guys,

Is it possible to specify a number of hosts for proxy and ignore others? Couldn't seem to find it anywhere.

The only thing I could think of is look up the ip of each host and then foreach/add them as endpoints?

Cheers

Marc

**Comment by justcoding121** [comment]
You can't do it. This is because a single TCP connection is usually used for multiple consecutive HTTP requests. However by default only request/response headers are parsed and body is relayed, so there is not going to be any notable performance difference by excluding hostnames.

However for HTTPS connections you could do that using ExcludedHttpsHostNameRegex property of the endpont. Assign a regex that will match not match desired hostnames, but will match excluded hostnames.

**Comment by marcfielding1** [comment]
Ahh, thanks for some reason I wasn't seeing the host name property yesterday after restarting visual studio I'm seeing it this morning :-)
