### ISSUE TITLE
Network Proxy with AD authentication

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#457]
Hello,
        I have a scenario, where there is a network proxy which authenticates a user using AD (Active Directory). When a user opens a browser and hits his first site, the browser prompts him to enter his windows login id and password.
I developed a windows service app which acts as local proxy (using Titanium proxy library). However, the prompt to enter the password stopped showing. 
I am aware that we can set the external proxy credentials as follows
```
_proxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = ip, Port = port };
_proxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = ip, Port = port };
_proxyServer.UpStreamHttpsProxy.UserName =userName;
_proxyServer.UpStreamHttpsProxy.Password = password;
_proxyServer.UpStreamHttpProxy.UserName = userName;
_proxyServer.UpStreamHttpProxy.Password = password;
```
But in my case I would like the user to enter is credentials everytime he hits his first url of the day.
How can I achieve this?

![image](https://user-images.githubusercontent.com/9862996/41104555-494d932a-6a89-11e8-873a-e565a3e09c42.png)

**Comment by Wintereise** [comment]
I can confirm that the proxy does respond with a 407 if a AuthenticateFunction has been assigned and returns false.

Though, your "first password of the day" use case likely will not work because it depends on the browsers caching credentials indefinitely for the day from that point on.

You can save yourself a lot of headache by simply using something like SwitchyOmega to achieve the browser integration (assuming Chrome).
