### ISSUE TITLE
Retrieve local EndPoint from ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by fabricedupre** [justcoding121/Titanium-Web-Proxy#460]
Hello,

Is there any way to retrieve the local EndPoint from a ServerCertificateValidationCallback ?

**Comment by justcoding121** [comment]
This is not straight forward to achieve, specifically because the callback is from [SslStream](https://msdn.microsoft.com/en-us/library/dd990420(v=vs.110).aspx). If we need to pass the object we may need to create a class with session as payload inheriting SslStream, so that it will be the sender object in the server certificate validation callback.

**Comment by honfika** [comment]
Now you can access the local endpoint from the CertificateValidationEventArgs parameter.
I close this issue, feel free to reopen/create new if needed.
