### ISSUE TITLE
git rebased?

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#491]
I'm trying to update my source tree which has some changes and it looks like your git commits were rebased or some other change occurred that altered the commit ids.

The last commit id that I have that matches is 5ac023d36c8acfab73f0edc7bf5716da75d30f3a from 9/29/2017.   After that your tree has 621c339fb4171897db0c2db5f6b4e3638ff78c07 but my original clone has ff0379d916af47210fd11ccc1b7266eb533228c0.

If you go into the github "insights" tab and look a the network you can also see that the clones are now pretty much disassociated from your branch.

Would it be possible for you to rebase back onto the original branch?

**Comment by justcoding121** [comment]
Given my poor expertise on git commands I am afraid I won't be able to go back. I had to rewriting commit history on few commits involving private email address.

This shouldn't prevent from creating PRs from your branch. Does it? Otherwise deleting, re-cloning and reinserting any PR changes would seem the only solution.

**Comment by justcoding121** [comment]
Also note that I moved source under a new parent root "src" folder to keep all solution files related to different run time in one folder. That was a major change.
