### ISSUE TITLE
Too many exceptions for system.IO.IOException

### ISSUE THREAD

**Issue by askerzhang** [justcoding121/Titanium-Web-Proxy#51]
There are many exception for System.IO.IOException when I run the proxy in my machine.
the detail information is "Unable to write data to the transport connection: An established connection was aborted by the software in your host machine."
I think it affects the performance

**Comment by justcoding121** [comment]
Since client or server can anytime terminate the underlying connection, we don't have any control over it. For example a browser may open ten connections and then it would decide to terminate all because the user closed the window or for some other reasons. That would throw ten exceptions as expected (which is caught and handled).

But if you think the design of the proxy causes this issue, we would like to address it.

**Comment by bonesoul** [comment]
same issue here.
