### ISSUE TITLE
ASP.NET Core Middleware

### ISSUE THREAD

**Issue by windischb** [justcoding121/Titanium-Web-Proxy#528]
Hi!

Is it possible to use this library in ASP.NET Core?
I have an existing API Service with a handfull HTTP Routes, which i would like to extend with a "reverse Proxy" functionality for a few other URL's.
The Goal is to have the API Routes and proxied Urls to other services an one single Service...

Thanks for any Ideas!
Br

**Comment by justcoding121** [comment]
You can use the library under ASP.Net core, since it targets netstandard. I am not sure what you are trying to accomplish. There is no way to push ASP.NET request directly to the proxy through a middleware. The proxy would listen on a port and you would need to forward ASP.NET requests to the port someway.
