### ISSUE TITLE
HTTPS didn`t work

### ISSUE THREAD

**Issue by kucja** [justcoding121/Titanium-Web-Proxy#542]
Win8, firefox (last), Titanium 3.0.878
HTTPS error - Код ошибки: SEC_ERROR_UNKNOWN_ISSUER

Code:
            _proxyServer = new Titanium.Web.Proxy.ProxyServer(true, true, true);
            _proxyServer.CertificateManager.CreateRootCertificate(true); //false to...
            _proxyServer.CertificateManager.TrustRootCertificate();
            _proxyServer.CertificateManager.TrustRootCertificateAsAdmin();

            ExplicitProxyEndPoint explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 8000);
            _proxyServer.AddEndPoint(explicitEndPoint);
            _proxyServer.Start();

What is my mistake???

**Comment by justcoding121** [comment]
You need to import the dummy root certificate the proxy generated to firefox manually. Firefox has its own certificate infrastructure and it won't respect windows certificate infrastructure.

**Comment by Mateos81** [comment]
Hello,

Windows 10, latest stable Firefox (x64), Titanium 3.0.895

I've followed the Mozilla documentation, that you can find here: https://github.com/mozilla/policy-templates/blob/master/README.md#certificates

In order to extract the certificate from Titanium (using SaveRootCertificate) in the right folder, then telling Firefox to import it using the Certificates Policy

So, at this point, I have the .pfx file in the Certificates folder in %USERPROFILE%\AppData\Local\Mozilla, and the policies.json file in the distribution folder next to the EXE file

When I open Firefox, I have the system proxy set, and the certificate is listed, but I still get like @kucja an SEC_ERROR_UNKNOWN_ISSUER error, while Edge and Chrome are OK (since they directly use system config, as you pointed)

The code is the same as in your ReadMe.md sample

Content of the policies.json file:
`{
    "policies": {
        "Certificates": {
            "ImportEnterpriseRoots": true,
            "Install": ["Titanium Root Certificate Authority.pfx"]
        }
    }
}`

Am I missing something else?

**Comment by danucalovj** [comment]
When you check Firefox's Certificate Manager, is it in the "Your Certificates" tab or "Authorities" tab? It should be under "Authorities".

Try doing the process manually. If you said Chrome works, here are the steps to export and import into Firefox. I just replicated these steps and it seems to work:

1. On Chrome, visit an https-enabled site, click on the certificate icon in the URL bar --> Certificate --> Certification Path and select the top-most certificate (CA), and click on View Certificate.
2. Now on that new window (the CA cert) go to Details and Copy to File. Do NOT select export private key, and export as a DER encoded binary (CER) file.
3. Open Firefox and import that certificate into the "Authorities" via Certificate Manager.

Tried that on my end and worked.

**Comment by Mateos81** [comment]
I need an automatic way to deploy on new computers, but yeah I had an entry in Your Certificates, and when I tried to import in Authorities Firefos first said it was already an authority though not listed, and after 3 clicks on Import it just asked for permissions and now it's listed and it works!

So I need a way to export from Titanium the Authority certificate? Simply .cer extension, or an other function?

**Comment by danucalovj** [comment]
Here's a good SO post on working with certificates in C#:

https://stackoverflow.com/questions/9810887/export-x509certificate2-to-byte-array-with-the-private-key

Or this:

https://stackoverflow.com/questions/4739407/exporting-a-certificate-as-base-64-encoded-cer

Once you've got the PFX those articles should help. I'd recommend closing this issue though it isn't directly related to TWP but rather certificate management in Firefox.

**Comment by honfika** [comment]
I close this issue, feel free to reopen/create new if needed.
