### ISSUE TITLE
sslStream not disposed; improve ProxyConnectException

### ISSUE THREAD

**Issue by jmh76** [justcoding121/Titanium-Web-Proxy#550]
`TransparentClientHandler` and `ExplicitClientHandler` only call `sslStream.Dispose()` when an exception is caught. It should do this in all cases, but without closing `clientStream`. I suggest the following: `new SslStream(clientStream, true)` to leave the inner stream open; add a `finally` block to dispose the `sslStream` when done. The inner stream will be closed when `clientStream.Dispose()` is called in the `finally` block at the end of the method.

Also, by not closing the `clientStream` before throwing a `ProxyConnectException`, the `ExceptionFunc` handler can report session info, if `TunnelConnectSessionEventArgs ConnectEventArgs` is changed to `SessionEventArgsBase Session` and set both from Explicit & Transparent handlers.

Creating pull request for these changes.

**Comment by justcoding121** [comment]
We call dispose() directly only when we have an exception, which means the connection is not good to reuse.

If no exception happened then then the server connection is released for reuse. See below line of code.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/RequestHandler.cs#L275

Inside the Release methods we call dispose() if connection cache is disabled. Otherwise its released to server connection cache. See below code.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L413

As far as client connection, its disposed when the request thread is about to exit. See below code.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/ProxyServer.cs#L737

**Comment by jmh76** [comment]
I was referring to the sslStream created here in TransparentClientHandler, similar in ExplicitClientHandler. This sslStream does not get Disposed. The underlying clientStream eventually does if not cached as you point out.

    if (endPoint.DecryptSsl && args.DecryptSsl)
    {

        SslStream sslStream = null;

        //do client authentication using fake certificate
        try
        {
            sslStream = new SslStream(clientStream);

            string certName = HttpHelper.GetWildCardDomainName(httpsHostName);
            var certificate = endPoint.GenericCertificate ??
                                    await CertificateManager.CreateServerCertificate(certName);

            // Successfully managed to authenticate the client using the fake certificate
            await sslStream.AuthenticateAsServerAsync(certificate, false, SslProtocols.Tls, false);

            // HTTPS server created - we can now decrypt the client's traffic
            clientStream = new CustomBufferedStream(sslStream, BufferPool, BufferSize);

            clientStreamWriter = new HttpResponseWriter(clientStream, BufferPool, BufferSize);
        }
        catch (Exception e)
        {
            sslStream?.Dispose();
            throw new ProxyConnectException(
                $"Could'nt authenticate client '{httpsHostName}' with fake certificate.", e, null);
        }
    }

**Comment by justcoding121** [comment]
Okay. Thanks.
