### ISSUE TITLE
Question: Modify Request

### ISSUE THREAD

**Issue by jpreese** [justcoding121/Titanium-Web-Proxy#60]
I'm trying to modify a request coming through Titanium Web Proxy, specifically modifying the querystring on a request.

I've tried setting my own Uri object on e.ProxySession.Request.RequestUri in OnRequest(), but it doesn't look like it is reflected in the browser.

**Comment by justcoding121** [comment]
When you say "reflected on browser" are you expecting the Url on browser to be changed? I don't think that would happen. What you would need to do that would be a custom response with a redirect to the new URL with the updated query string.

**Comment by jpreese** [comment]
Yeah, I was looking at just redirecting the request as well, but didn't see any sort of Redirect() method available.

**Comment by justcoding121** [comment]
You can use the [respond method](https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs#L430) to redirect with a custom response.

Notice that our [Ok() method](https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs#L389) uses the generic responder method. Instead of 200 Ok responder you would need to use a [redirect response code](https://en.wikipedia.org/wiki/URL_redirection#Example_HTTP_response_for_a_301_redirect).

**Comment by justcoding121** [comment]
We can add a redirect method in future

**Comment by justcoding121** [comment]
Added in #64 on beta
