### ISSUE TITLE
Track data used per request

### ISSUE THREAD

**Issue by ByronAP** [justcoding121/Titanium-Web-Proxy#626]
I am trying to keep track of the amount of data a request uses... end to end. for http I can add up the request and response content length which seems fairly accurate and just needs to have header length added. This however will not work with https because i am not decrypting it.

I am thinking a better way is to keep track using the underlying stream but really i am not sure how to make that work... maybe a new long added to the httpclient... any suggestions @honfika ?

**Comment by honfika** [comment]
There is a DataReceived and DataSent event. See this example:

https://github.com/justcoding121/Titanium-Web-Proxy/blob/ba428196aa2be2c45fb68bdc9cb82cfe5eb238ee/examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs#L234-L262

**Comment by ByronAP** [comment]
🍌 🙇

**Comment by honfika** [comment]
I have improved it a little bit (in the latest beta package)

There is (+ was) a `BeforeTunnelConnectRequest` event (probably you already noticed that), it receives a `TunnelConnectSessionEventArgs` parameter.
It has 4 events: 
- `DataSent`: gets all encrypted data sent by the proxy client except the Tunnel Connect header (since it is passed to the event, so it shoudl be read before), also includes the SSL header (clienthello) bytes
- `DataReceived`: gets all the data received from the webserver. also includes the connect header and the the SSL header (Serverhello, etc)
- `DecryptedDataSent`: gets the sent bytes of the decrypted SSL stream (from the client). this is always less than the `DataSent `bytes
- `DecryptedDataReceived`: gets the received bytes of the decrypted SSL stream (from the web server). this is always less than the `DataReceived `bytes

There is another event in the `ProxyServer` object, called `BeforeRequest`:
It received a `SessionEventArgs` parameter, which has 2 events:
- `DataSent`: gets the body bytes of the HTTP (pure or over SSL) request, so you need to add the header bytes
- `DataReceived`: gets the body bytes of the HTTP (pure or over SSL) resposne, so you need to add the header bytes

**Comment by ByronAP** [comment]
i'm thinking about adding an event to session the fires when the session is completed which i figured would be easy to see when dispose gets called on session or session base but for some reason the dispose never fires...

**Comment by ByronAP** [comment]
ok so here is the issue... when the call is transparent the session changes so the httpclient and any user data gets lost making it impossible to keep track of the data used by setting userdata or adding extra info such as the username/auth used to the session.

**Comment by honfika** [comment]
:( I not really now how to make trasnparent requests, if you can make a PR I'll check it and merge it.

**Comment by ByronAP** [comment]
closing to make a new clean issue
