### ISSUE TITLE
Running As Service 

### ISSUE THREAD

**Issue by mmorales0113** [justcoding121/Titanium-Web-Proxy#670]
I'm trying to run Titanium Web Proxy as windows service. Is this possible? The service starts but nothing registers. Wondering if a solution has been found. Appreciate it.

**Comment by ByronAP** [comment]
This is a common use case and should not be an issue. You will need to make sure that if enabling certificate trust the service is running privileged.

I'll upload an example in a minute.

**Comment by ByronAP** [comment]
SEE: #671

**Comment by mmorales0113** [comment]
Try this solution but I'm getting the same outcome. I don't see the proxy set on Windows or anything registering.

**Comment by mmorales0113** [comment]
Noticed in the logs I'm getting this Event
Unhandled Exception in ProxyServer, Exception = System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights. ---> System.Security.Cryptography.CryptographicException: The request is not supported.

   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation) in C:\source\repos\Titanium-Web-Proxy\src\Titanium.Web.Proxy\Network\CertificateManager.cs:line 324
   --- End of inner exception stack trace ---

**Comment by ByronAP** [comment]
you need to make the service run as a privileged user  like administrator, this will allow the certificate to be trusted. Then you need to add code in the service start to set it as the system proxy. An example of doing this is found in the other example projects. 

SEE: https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs#L103

**Comment by ByronAP** [comment]
You can also tell windows to use the proxy by manually setting it in the windows system settings to use 127.0.0.1:8080 or whatever you have set in the service config file (ListeningPort).

SEE: https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/examples/Titanium.Web.Proxy.Examples.WindowsService/Properties/Settings.settings#L6

**Comment by sideup66** [comment]
Hi Byron,
Sorry to hijack an issue thread but im a bit confused here, i have a similar thing with the root certificate not being trusted due to permissions. i did look at your code example, and have my own code that does work, however im not sure how to set the permission to administrator on a box or -what- specific permissions the application needs to run. I am hoping that there is an answer to this. my application also has a service installer and currently uses  System.ServiceProcess.ServiceAccount.LocalSystem . any advice would be appreciated. thanks!

**Comment by ByronAP** [comment]
If I am understanding you correctly then yes LocalSystem doesn't have permission to do much let alone install a certificate. IMHO, since you already have an installer I would make a cert that gets installed to the machine store during installation and use this same cert in your proxy code. Hope that makes sense. It is safer and easier than being bothered with changing or granting permissions.

**Comment by sideup66** [comment]
Hi, 
Yes, it does make sense about user accounts. What is interesting in this, is that i tested by using my own login account to windows, which is a member of administrators group as a test... and even then the certificate error still presents itself. the next point i am trying to figure out in code, is how to add the endpoints and start the proxy while having it not mess with certificates, or use one already in the store? thanks!

**Comment by ByronAP** [comment]
I'm not quite sure what you mean by not mess with certificates... 
To use your own certificate:

```ProxyServerInstance.CertificateManager.LoadRootCertificate("c:\\proxy_cert.pfx", "cert-password");```

To add listening endpoints you can do it like so:

```
var myExplicitEndpoint = new ExplicitProxyEndPoint(IPAddress.Any, 1080, false);

ProxyServerInstance.AddEndPoint(myExplicitEndpoint);
```

**Comment by sideup66** [comment]
Sorry I was unclear, what I mean is, I am trying to see if potentially there is a manual way to add the certificate to the root store before titanium starts, so it won't bother with trying to add a certificate. I have tried to add a cert previously, and found that it did add, but the error , Exception = System.Exception: Failed to make system trust root certificate for Root\CurrentUser store location. You may need admin rights. Still persists. More interesting, was that as a test, I tried to make the service run under my own login account, which has administrator rights, and I still recieved the error.

Is there a way to have titanium use a certificate already in the store rather than trying to add it in at runtime? As in directly point to a certificate in the root store? I'm assuming once past that point, setting the proxy as the default should be do able as a service account as local system seems to have access to the filesystem. Thanks!

**Comment by mmorales0113** [comment]
I was able to get the service going by installing the certificate in Personal\Certificates and in Trusted Root Certification Authorities\Certificate. You must run the service as an Administrator.

**Comment by sideup66** [comment]
Hi mmorales,
That is the issue I'm coming across, as I cannot figure out how to make the service run as administrator, when I tested previously using my login account (which has admin credentials) it did not work.... Do I need to use the built in administrator account? Thanks

**Comment by mmorales0113** [comment]
Now I'm trying to log/block traffic. 

I added this line to the OnStart Method

            _proxyServerInstance.BeforeRequest += onRequest;

Then created a method as follows:
private async Task onRequest(object sender, SessionEventArgs e)
        {
            ProxyServiceEventLog.WriteEntry($"Website Information {e.HttpClient.Request.RequestUri.AbsoluteUri}", 0);

            if (e.HttpClient.Request.RequestUri.AbsoluteUri.Contains("yahoo.com"))
            {
                e.Ok("<!DOCTYPE html>" +
                      "<html><body><h1>" +
                      "Website Blocked" +
                      "</h1>" +
                      "<p>Blocked by titanium web proxy.</p>" +
                      "</body>" +
                      "</html>");
            }
        }

Not sure if this is correct.

**Comment by mmorales0113** [comment]
For testing purposes, try adding the user to the local admin group.

**Comment by mmorales0113** [comment]
I'm unable to intercept traffic/block websites. I have tried the following:
Added this code to the OnStart method
  _proxyServerInstance.BeforeRequest += onRequest;

Created this Method as well:

private async Task onRequest(object sender, SessionEventArgs e){
            ProxyServiceEventLog.WriteEntry($"Website Information {e.HttpClient.Request.RequestUri.AbsoluteUri}", 0);

            if (e.HttpClient.Request.RequestUri.AbsoluteUri.Contains("yahoo.com"))
            {
                e.Ok("<!DOCTYPE html>" +
                      "<html><body><h1>" +
                      "Website Blocked" +
                      "</h1>" +
                      "<p>Blocked by titanium web proxy.</p>" +
                      "</body>" +
                      "</html>");
            }
        }
Appreciate any help available.

**Comment by sideup66** [comment]
Hi, 
I did just perform a test starting my service as administrator with the certificate in the store, unfortunately i ran into the same error. Im beginning to think with the issues that titanium web proxy simply cannot be used as a service proxy unfortunately. This is something that should be reviewed and tested further. My machine is running windows 10 1903 for reference.

**Comment by sideup66** [comment]
mmorales, in my test, i was able to get my filtering to work by placing it in my onrequestasync method:


`       private async Task OnRequestAsync(object sender, SessionEventArgs e)
        {


            //To cancel a request with a custom HTML content
            //Filter URL
            foreach(string item in sitelist)
            {
                if (e.HttpClient.Request.RequestUri.AbsoluteUri.Contains(item))
                {
                    e.Ok("<!DOCTYPE html>" +
                          "<html><body><h1>" +
                          "Website Blocked" +
                          "</h1>" +
                          "<p>Blocked by Ontrak Distraction Blocker!</p>" +
                          "</body>" +
                          "</html>");
                }

            }

            ////Redirect example
            //if (e.HttpClient.Request.RequestUri.AbsoluteUri.Contains("wikipedia.org"))
            //{ 
            //   e.Redirect("https://www.paypal.com");
            //} 

        }`

and i need to tell titanium in my case when to intercept and decrypt a page. put this in 👍 

`  private static async Task OnBeforeTunnelConnectRequest(object sender, TunnelConnectSessionEventArgs e)
        {
            string hostname = e.HttpClient.Request.RequestUri.Host;
            //Console.WriteLine("Tunnel to: " + hostname);

            if (!hostname.Contains("youtube.com"))
            {
                //we only allow the proxy to intercept blocked sites. this helps performance tremendously
                e.DecryptSsl = false;
            }

        }`

to declare it in titanium run the following when your setting up your proxy:

`                    proxyServer.BeforeRequest += OnRequestAsync;
`
`                    explicitEndPoint.BeforeTunnelConnectRequest -= OnBeforeTunnelConnectRequest;
`

**Comment by sideup66** [comment]
Hi,
As for my problem, I did test using my administrator credentials, however the service still threw the same error. I have gone and made sure i am loading an existing one that is in the same folder as the executable, and even ran a check against the                     
IsRootCertificateMachineTrusted();
and 
IsRootCertificateUserTrusted()
booleans to see if the certificate is indeed trusted, and both return true, however, it seems that titanium is insistant on trusting the certificate, which i am not understanding, if the booleans are indeed true, should it not? is there a way to have titanium just skip trying to trust the certificate already (as a condition of being a service i can indeed have the service installed with its own certificate so its already present before it runs, thus should negate the need for root. I think this is where the problem lies. For some reason, titanium web proxy just seems insistant on trusting the certificate despite the fact of it already existing in the root store. Is there a way to make pendulum stop trying to load the certificate?

**Comment by sideup66** [comment]
Sorry for the pile of updates,

After a bit more digging, I was able to stop the certificate error, by setting the following:
 
proxyServer.CertificateManager.EnsureRootCertificate(false, false, false);

According to here, https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.Network.CertificateManager.html it appears to stop the certificate checks or the process of making things root (which they were manually set to, now the issue I am coming across is that 1. it will not set itself to the system proxy and 2. it seems to return empty responses when i try to use the proxy. Not sure where to go from here, but it seems i have progress. If i can get the proxy to start talking to me, I might be able to get this working without administrator privileges. Any help there would be appreciated. Thanks!

**Comment by mmorales0113** [comment]
Haven't been able to block or log website traffic. I was able to get the proxy started but unable to intercept and block web traffic. Please help!
