### ISSUE TITLE
fillbufferAsync Cannot access disposed object

### ISSUE THREAD

**Issue by mmorales0113** [justcoding121/Titanium-Web-Proxy#697]
I'm getting a lot of exception on fillbufferAsync method:
Cannot access a disposed object. I updated to the latest proxy version. Exception points to this line 

            bool result = false;
            try
            {
                int readBytes = await baseStream.ReadAsync(streamBuffer, bufferLength, bytesToRead, cancellationToken);
                result = readBytes > 0;
                if (result)
                {
                    OnDataRead(streamBuffer, bufferLength, readBytes);
                    bufferLength += readBytes;
                }
            }
            catch(Exception e)
            {
                if (!swallowException)
                    throw;
            }
            finally
            {
                if (!result)
                {
                    closedRead = true;
                    closedWrite = true;
                }
            }

**Comment by honfika** [comment]
Do you use .NET Framework? I suggest you to upgrade to .NET Core if possible, since there is a problem with the async read in .NET Framework, it is not possible to cancel it... so there is an ObjectDisposed exception when you dispose the client stream (regardless of whether the token which was passed to the ReadAsync method was cancelled or not)

**Comment by honfika** [comment]
Also please try the next beta package, maybe it is better a little bit.

**Comment by honfika** [comment]
I close this issue due to inactivity, feel free to reopen/create new if needed.
