### ISSUE TITLE
How to get request and response body length of a ssl non decrypted session

### ISSUE THREAD

**Issue by OverFlow170** [justcoding121/Titanium-Web-Proxy#827]
Here we are, I'm stuck with SSL issue for two days now.
I have exactly the same problem as the issue: #478

"I want to deploy the proxy server on a remote server and have clients configure their proxy settings to go through that proxy. Ideally, The clients should be able to just enter the proxy info in their proxy config and **not have to manually install a certificate on the client.** Are there concrete examples of how to do this?"

**As I need to know the lenght of the body of the request response**. And I can't do that if `e.DecryptSsl = false;`.

**Comment by DiegoCarrilho** [comment]
Certificate installation is mandatory to decrypt ssl.

**Comment by OverFlow170** [comment]
Ok thank you.

and is there a way to see the length of queries without decrypting ssl ?

**Comment by DiegoCarrilho** [comment]
Do You mean Request and Response Body length of a ssl non decrypted session? I cant figure out.

**Comment by OverFlow170** [comment]
Yes request + response body length

**Comment by DiegoCarrilho** [comment]
Since no ssl decrypt case are sent as raw, i think it’s possible. Btw, is there many easy ways to write a simple http proxy to reach the goal, like the Synapse Library for Delphi.

**Comment by OverFlow170** [comment]
```
clientStream.DataRead += (o, args) => connectArgs.OnDataSent(args.Buffer, args.Offset, args.Count);
clientStream.DataWrite += (o, args) => connectArgs.OnDataReceived(args.Buffer, args.Offset, args.Count);
```

All i found are these two events but buffer.length seem to be inaccurate

**Comment by honfika** [comment]
When you are not decrypting the SSL stream you have only a bi-directional stream, so you can't know when is the end of a request.
So you can't get the size of the unique request/resposne... however you could know the total size of the requests/responses. (which contains all HTTP queries to the same server)
This is what you get with the DataRead/DataWrite methods (you have to sum all values, because it receives chunks). The chunk does not mean anything.. it can be a whole response or a partial response or even multiple responses (or a partial response + another partial or full response), so anything...

Of course if you are sure that there is only 1 request/resposne, the total size is the size of that request/response.. maybe with adding some header size for the SSL authentication... so it is not an accurate number, just approximately.

**Comment by OverFlow170** [comment]
Okay, thank you very much, by the way the code is very well done!
