### ISSUE TITLE
Read request data in response event?

### ISSUE THREAD

**Issue by KirovAir** [justcoding121/Titanium-Web-Proxy#91]
Hello,

I would like to access data from the request in the response event. Currently this is not possible it seems. 
Making the WebSession.Request.RequestBody a public property will fix this it seems? (When I will call the GetRequestBody() in the request event)

Or am I thinking wrong here?

Thanks for this awesome library! :)

**Comment by KirovAir** [comment]
I made some small changes in the code to make this possible. Should not affect anything. :)

**Comment by justcoding121** [comment]
The change you made would break our design assumption. Once request is send to server we don't have it anywhere. Its gone.

In your case probably you were able to access the request body because your read it before sending the request. The request body is only available if the user decided to read the request body before request. Otherwise its simply relayed to server. This is to prevent unnecessary memory pressure on proxy.

So a better solution would be you to read the request before its send to server and have the request body stored in a dictionary and then access it on response handler.

**Comment by KirovAir** [comment]
It's true what you say. I am (pre) reading it in the request now. But shouldn't the WebSession.Request.RequestLocked prevent give the user an error before it was read anyway in case they don't do that?

Anyway, I understand the design choice. And again thanks for the awesome proxy again. :+1:

**Comment by justcoding121** [comment]
Okay I will take a look asap and get back with you. Thanks.

**Comment by justcoding121** [comment]
Good work. Merged in.  :+1:
